version: '2'

services:
  server:
    build: .
    volumes:
      - ./conf.js:/app/conf.js
      - ./extensions:/app/extensions
    command: [ "trade", "--paper" ]
    restart: always
    tty: true
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data
    command: mongod --smallfiles
    #
  # Remove below comments to use this container. "adminMongo is a Web based user interface (GUI) to handle all your MongoDB connections/databases needs."
  #
  #adminmongo:
  #  image: mrvautin/adminmongo
  #  links:
  #    - mongodb
  #  tty: true
  #  ports:
  #    - "1234:1234"
  #  environment:
  #    - CONN_NAME=zenbot_mongodb
  #    - DB_HOST=mongodb
  #    - DB_PORT=27017
  #  command: "npm start"

volumes:
  mongodb-data:


